# Generated by Django 3.1 on 2020-08-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0003_auto_20200825_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
