# Generated by Django 3.1 on 2020-08-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0004_auto_20200825_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('position', models.CharField(choices=[('S', 'Sprzedawca'), ('SB', 'Sprzedawca/Biuro'), ('B', 'Biuro'), ('D', 'Dyrektor')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=64)),
                ('comments', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[], default=1)),
                ('expirationDate', models.DateField()),
                ('itemsCount', models.IntegerField(null=True)),
                ('calculationUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculationUser', to='opakowania.user')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdBy', to='opakowania.user')),
                ('customerAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opakowania.address')),
                ('customerContact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opakowania.contact')),
            ],
        ),
    ]
