# Generated by Django 3.1 on 2020-10-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0008_auto_20201010_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='NIP'),
        ),
    ]
