# Generated by Django 3.1 on 2020-10-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0011_auto_20201014_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='expirationDate',
        ),
    ]
