# Generated by Django 3.1 on 2020-10-17 12:02

from django.db import migrations, models
import django.db.models.deletion
import opakowania.models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0015_auto_20201016_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa produktu')),
                ('index', models.CharField(max_length=64, verbose_name='Indeks produktu')),
                ('primary', models.BooleanField(default=False, verbose_name='Produkt główny')),
                ('form', models.BooleanField(default=False, verbose_name='Fason')),
                ('laminating', models.BooleanField(default=False, verbose_name='Kaszerowanie')),
                ('solid', models.BooleanField(default=False, verbose_name='Lita')),
                ('flexoOverprint', models.BooleanField(default=False, verbose_name='Nadruk Flexo')),
                ('refinement', models.BooleanField(default=False, verbose_name='Uszlachetnianie')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('depth', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='comments',
            field=models.TextField(verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='expirationDate',
            field=models.DateField(default=opakowania.models.Offer.now_plus_month, verbose_name='Data wygaśnięcia'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='itemsCount',
            field=models.IntegerField(default=0, null=True, verbose_name='Ilość produktów'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.IntegerField(choices=[(1, 'Nowa')], default=1, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opakowania.offer')),
            ],
        ),
    ]
