# Generated by Django 3.1 on 2020-10-17 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0016_auto_20201017_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='product',
            name='index',
        ),
        migrations.AddField(
            model_name='product',
            name='commentJoin',
            field=models.CharField(blank=True, max_length=64, verbose_name=''),
        ),
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Uwagi dodatkowe'),
        ),
        migrations.AddField(
            model_name='product',
            name='contactPerson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opakowania.contact', verbose_name='Osoba kontaktowa'),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryAddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opakowania.address', verbose_name='Adres dostawy'),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryVariantOne',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wariant 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryVariantThree',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wariant 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryVariantTwo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wariant 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='deliveryYearly',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ilość roczna'),
        ),
        migrations.AddField(
            model_name='product',
            name='gluedJoin',
            field=models.BooleanField(default=False, verbose_name='Łączenie klejone'),
        ),
        migrations.AddField(
            model_name='product',
            name='innerIndex',
            field=models.CharField(blank=True, max_length=128, verbose_name='Indeks wewnętrzny'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Długość'),
        ),
        migrations.AddField(
            model_name='product',
            name='mixedJoin',
            field=models.BooleanField(default=False, verbose_name='Łączenie inne'),
        ),
        migrations.AddField(
            model_name='product',
            name='numberOfElements',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Pudło z części'),
        ),
        migrations.AddField(
            model_name='product',
            name='offsetOverprint',
            field=models.BooleanField(default=False, verbose_name='Nadruk Offset'),
        ),
        migrations.AddField(
            model_name='product',
            name='outsideIndex',
            field=models.CharField(blank=True, max_length=128, verbose_name='Indeks zewnętrzny'),
        ),
        migrations.AddField(
            model_name='product',
            name='sewnJoin',
            field=models.BooleanField(default=False, verbose_name='Łączenie szyte'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizeType',
            field=models.IntegerField(choices=[(1, 'Wewnętrzny'), (2, 'Zewnętrzny'), (3, 'Mieszany')], default=1, verbose_name='Wymiar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Wysokość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Szerokość'),
        ),
    ]
