# Generated by Django 3.1 on 2020-10-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0017_auto_20201017_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='itemsCount',
        ),
        migrations.AddField(
            model_name='offer',
            name='numberOfPositions',
            field=models.IntegerField(default=0, null=True, verbose_name='Ilość pozycji'),
        ),
        migrations.AddField(
            model_name='position',
            name='numberOfProducts',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość produktów'),
        ),
        migrations.AddField(
            model_name='position',
            name='orderNumberInOffer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='orderNumberInPosition',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='opakowania.position'),
            preserve_default=False,
        ),
    ]
