# Generated by Django 3.1 on 2020-10-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0018_auto_20201019_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ostaniej edycji'),
        ),
    ]
