# Generated by Django 3.1 on 2020-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0021_auto_20201019_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='position',
            name='deletedDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='deletedDate',
            field=models.DateField(null=True),
        ),
    ]
