# Generated by Django 3.1 on 2020-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0023_auto_20201021_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='activeProducts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
