# Generated by Django 3.1 on 2020-10-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0027_auto_20201024_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orderNumberInPosition',
            field=models.IntegerField(),
        ),
    ]
