# Generated by Django 3.1 on 2020-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0028_auto_20201024_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='numberOfProducts',
            field=models.PositiveIntegerField(verbose_name='Ilość produktów'),
        ),
    ]
