# Generated by Django 3.1 on 2020-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0029_auto_20201024_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='numberOfProducts',
            field=models.PositiveIntegerField(null=True, verbose_name='Ilość produktów'),
        ),
    ]
