# Generated by Django 3.1 on 2020-08-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addres',
            new_name='Address',
        ),
    ]
