# Generated by Django 3.0.7 on 2020-10-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0006_auto_20201003_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=64, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=64, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='address',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Główny'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=10, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=64, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='position',
            field=models.CharField(max_length=64, null=True, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Główny'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(null=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nazwa klienta'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_code',
            field=models.CharField(max_length=20, verbose_name='NIP'),
        ),
    ]
