# Generated by Django 3.1 on 2020-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0010_auto_20201014_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='itemsCount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
