# Generated by Django 3.1 on 2020-10-16 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0012_remove_offer_expirationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expirationDate',
            field=models.DateField(default=datetime.date(2020, 10, 16)),
        ),
    ]
