# Generated by Django 3.1 on 2020-10-16 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0013_offer_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expirationDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
