# Generated by Django 3.1 on 2020-10-16 08:44

from django.db import migrations, models
import opakowania.models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0014_auto_20201016_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expirationDate',
            field=models.DateField(default=opakowania.models.Offer.now_plus_month),
        ),
    ]
