# Generated by Django 3.1 on 2020-10-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0019_offer_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='edited',
            new_name='lastModified',
        ),
    ]
