# Generated by Django 3.1 on 2020-10-19 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0020_auto_20201019_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ostaniej edycji'),
        ),
    ]
