# Generated by Django 3.1 on 2020-10-21 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0022_auto_20201021_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data utworzenia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='Data ostaniej edycji'),
        ),
        migrations.AlterField(
            model_name='position',
            name='deletedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Usunięto?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deletedDate',
            field=models.DateTimeField(null=True, verbose_name='Data usunięcia'),
        ),
    ]
