# Generated by Django 3.1 on 2020-10-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opakowania', '0025_position_deletedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='activePositions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offer',
            name='deletedPositions',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
